// This program is created by shadow leaked
#include<iostream.h>
#include<dos.h>
//dos.h is for delay, sound and nosound function.
#include<conio.h>

	void main()
{
	clrscr(); // To clear the screen.
int x,y;
cout<<"\nEnter password for security purpose\n\n";
cout<<":";cin>>x;
delay(1000);
if(x==0)//password = 0
	{
	cout<<"\n";

	cout<<"A";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"C";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"C";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"E";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"S";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"S";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<" ";                                          delay(200);
	cout<<"G";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"R";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"A";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"N";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"T";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"E";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	cout<<"D";/*{sound(1300); delay(500); nosound();}*/ delay(200);
	delay(1000);
cout<<"\n\nPLEASE WAIT\n"; // Output command
	delay(2000); // Making the system delay for 1 sec
cout<<"\nALL"; delay(200);
cout<<" SYSTEM"; delay(200);
cout<<" INITIALIZING ";
	delay(1000);
cout<<".";
	{sound(5000); delay(500); nosound();}
       delay(500);
cout<<".";
	 {sound(5000); delay(500); nosound();}
	delay(500);
cout<<". \n";
	{sound(5000); delay(500); nosound();}
	delay(1000);
cout<<"\nALL SYSTEM FOR S.H.I.E.L.D IS ONLINE\n";
	delay(2500);
cout<<"\nWAITING FOR YOUR COMMAND DIRECTOR\n\n";

cout<<":";cin>>y;


	if(y==101){      //Protocol 101 system total shutdown
		cout<<"\nI"; delay(200);
		cout<<"N"; delay(200);
		cout<<"I"; delay(200);
		cout<<"T"; delay(200);
		cout<<"I"; delay(200);
		cout<<"A"; delay(200);
		cout<<"T"; delay(200);
		cout<<"I"; delay(200);
		cout<<"N"; delay(200);
		cout<<"G"; delay(200);
		cout<<" "; delay(200);
		cout<<"P"; delay(200);
		cout<<"R"; delay(200);
		cout<<"O"; delay(200);
		cout<<"T"; delay(200);
		cout<<"O"; delay(200);
		cout<<"C"; delay(200);
		cout<<"O"; delay(200);
		cout<<"L"; delay(200);
		cout<<" "; delay(200);
		cout<<"1"; delay(200);
		cout<<"0"; delay(200);
		cout<<"1\n"; delay(200);
		cout<<"\n"; delay(400);
		cout<<"A"; delay(200);
		cout<<"L"; delay(200);
		cout<<"L"; delay(200);
		cout<<" "; delay(200);
		cout<<"S"; delay(200);
		cout<<"Y"; delay(200);
		cout<<"S"; delay(200);
		cout<<"T"; delay(200);
		cout<<"E"; delay(200);
		cout<<"M"; delay(200);
		cout<<" "; delay(200);
		cout<<"I"; delay(200);
		cout<<"N"; delay(200);
		cout<<" "; delay(200);
		cout<<"L"; delay(200);
		cout<<"O"; delay(200);
		cout<<"C"; delay(200);
		cout<<"K"; delay(200);
		cout<<"D"; delay(200);
		cout<<"O"; delay(200);
		cout<<"W"; delay(200);
		cout<<"N"; delay(500);

	}
	else if(y==102){
	cout<<"\nPROTOCOL"<<" "<<"102";
	}
	else{
	cout<<"\nPROTOCOL "<<y;
	}
}                    else{cout<<"\nA"; delay(200);
			  cout<<"C";   delay(200);
			  cout<<"C";   delay(200);
			  cout<<"E";   delay(200);
			  cout<<"S";   delay(200);
			  cout<<"S";   delay(200);
			  cout<<" ";   delay(200);
			  cout<<"D";   delay(200);
			  cout<<"E";   delay(200);
			  cout<<"N";   delay(200);
			  cout<<"I";   delay(200);
			  cout<<"E";   delay(200);
			  cout<<"D";   delay(200);

			 }
	getch();
}
