// This program is created by shadow leaked
#include<iostream.h>
#include<dos.h>
//dos.h is for delay, sound and nosound function.
#include<conio.h>

	void main()
{
	clrscr(); // To clear the screen.
	delay(2000);
cout<<"\nWelcome back Captain \n"; // Output command
	delay(2000); // Making the system delay for 1 sec
cout<<"\nAll system initializing ";
	delay(1000);
cout<<".";
	{sound(800); delay(500); nosound();}
       delay(500);
cout<<".";
	 {sound(800); delay(500); nosound();}
	delay(500);
cout<<". \n";
	{sound(800); delay(500); nosound();}
cout<<"\nJarvis is online sir\n";
	delay(1600);
cout<<"\nWaiting for your command\n";
	getch();
}
